### ISSUE TITLE
Using Babel & babel-loader, require('split-human-name') returns {} (empty object)

### ISSUE THREAD

**Issue by ceefour** [compwright/split-human-name#12]
The problem is likely https://stackoverflow.com/a/38290798/122441

It gives a fix for Webpack. I don't how to fix this in Parcel.

Example project that uses Babel & babel-loader is Ant Design Pro V5.

**Comment by compwright** [comment]
@ceefour I'm happy to try to help you fix this, especially if it's a problem with my build configuration; however I'll need gist that reproduces the problem. Include all relevant files—package.json, Webpack config, Babel config, etc. Or if you find a fix, I'd be happy to review a pull request.
